1. adjust the templates to enable im_calc automation. 2. adjust set_runparams import params 3. modify the test code to fit binary hf and bb.

diff --git a/templates/im_calc.sl.template b/templates/im_calc.sl.template
--- a/templates/im_calc.sl.template
+++ b/templates/im_calc.sl.template
@@ -10,21 +10,25 @@ echo "script started running at: $script_start"
 echo ___calculating simulations___
 {% for sim_dir, sim_name, fault_name in sim_dirs %}
     echo {{sim_dir}}
+    #update db to running
+    timestamp=`date +%Y%m%d_%H%M%S`
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation running --run_name {{sim_name}} --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+    #run the script
     time python2 $IMPATH/calculate_ims.py {{sim_dir}}/Acc/BB.bin b -o {{sim_dir}}/../../../IM_calc/ -np {{np}} -i {{sim_name}} -r {{fault_name}} -c {{comp}} -t s {{extended}} {{simple}}
 
 #test before update mgmt_db
-timestamp=`date +%Y%m%d_%H%M%S`
-res=`python $gmsim/workflow/scripts/im_cal_checkpoint.py {{sim_dir}} {{fault_name}} --t s --v `
+    timestamp=`date +%Y%m%d_%H%M%S`
+    res=`python $gmsim/workflow/scripts/im_calc_checkpoint.py {{mgmt_db_location}}/Runs {{fault_name}} --t s --v `
 #update mgmt_db
-if [[ $? == 0 ]]; then
-    #passed
-    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation completed --r {{fault_name}} --force" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
-    #save metadata for collection
-    #
-else
-    #failed
-    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation failed --r {{fault_name}} --error '$res' --force"  >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
-fi
+    if [[ $? == 0 ]]; then
+        #passed
+        echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation completed --run_name {{sim_name}} --force" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+        #save metadata for collection
+        #
+    else
+        #failed
+        echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation failed --run_name {{sim_name}} --error '$res' --force"  >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+    fi
 {% endfor %}
 {% endif %}
 
