refactored testing codes to fit the newest automatic workflow. edited some of the submit scripts to contain extra values needed for testing scripts

diff --git a/templates/post_emod3d_merge_ts.sl.template b/templates/post_emod3d_merge_ts.sl.template
--- a/templates/post_emod3d_merge_ts.sl.template
+++ b/templates/post_emod3d_merge_ts.sl.template
@@ -16,6 +16,12 @@ OUTFILE=`head -1 $filelist  |sed -e 's/-[0-9]*.e3d/.e3d/g'`
 echo "NFILES=$NFILES OUTFILE=$OUTFILE"
 time srun $exe filelist=$filelist outfile=$OUTFILE nfiles=$NFILES
 
-#TODO: add in test
 timestamp=`date +%Y%m%d_%H%M%S`
-echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} merge_ts completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+#test before update
+res=`$gmsim/deploy/slurm_gm_workflow/scripts/test_merge_ts.sh {{sim_dir}} {{srf_name}}`
+if [[ $? == 0 ]]; then
+    #passed
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} merge_ts completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+else
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} merge_ts failed --j $SLURM_JOBID --error '$res'" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+fi
diff --git a/templates/post_emod3d_winbin_aio.sl.template b/templates/post_emod3d_winbin_aio.sl.template
--- a/templates/post_emod3d_winbin_aio.sl.template
+++ b/templates/post_emod3d_winbin_aio.sl.template
@@ -12,9 +12,15 @@ echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_loca
 srun python $BINPROCESS/winbin-aio-mpi.py {{lf_sim_dir}}
 #srun python $BINPROCESS/winbin-aio.py {{lf_sim_dir}}
 
-#TODO: add in test
 date
 timestamp=`date +%Y%m%d_%H%M%S`
-echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} winbin_aio completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+#test before update
+res=`$gmsim/deploy/slurm_gm_workflow/scripts/test_winbin_aio.sh {{sim_dir}} {{srf_name}}`
+if [[ $? == 0 ]]; then
+    #passed
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} winbin_aio completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+else
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} winbin_aio failed --j $SLURM_JOBID --error '$res'" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+fi
 
 
diff --git a/templates/run_bb_mpi.sl.template b/templates/run_bb_mpi.sl.template
--- a/templates/run_bb_mpi.sl.template
+++ b/templates/run_bb_mpi.sl.template
@@ -14,7 +14,14 @@ srun python  $BINPROCESS/match_seismo-mpi.py $bb_sim_dir
 
 date
 timestamp=`date +%Y%m%d_%H%M%S`
-echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} BB completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+#test before update
+res=`$gmsim/deploy/slurm_gm_workflow/scripts/test_bb.sh {{sim_dir}} {{hf_run_name}} {{srf_name}}`
+if [[ $? == 0 ]]; then
+    #passed
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} BB completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+else
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} BB failed --j $SLURM_JOBID --error '$res'" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+fi
 ##echo "Making .tar out of Vel and Acc files"
 ##here=`pwd`
 ##cd $bb_sim_dir
diff --git a/templates/run_emod3d.sl.template b/templates/run_emod3d.sl.template
--- a/templates/run_emod3d.sl.template
+++ b/templates/run_emod3d.sl.template
@@ -14,9 +14,15 @@ srun {{tools_dir}}/emod3d-mpi -args "par={{lf_sim_dir}}/e3d.par"
 export end=`date +%H:%M:%S_%d/%m/%Y`
 echo $end
 #run test script and update mgmt_db
-#python $gmsim/workflow/scripts/test_and_update.py EMOD3D {{lf_sim_dir}} {{mgmt_db_location}} $SLURM_JOBID
+#test before update
 timestamp=`date +%Y%m%d_%H%M%S`
-echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} EMOD3D completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+res=`$gmsim/deploy/slurm_gm_workflow/scripts/test_emod3d.sh {{sim_dir}} {{srf_name}}`
+if [[ $? == 0 ]]; then
+    #passed
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} EMOD3D completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+else
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} EMOD3D failed --j $SLURM_JOBID --error '$res'" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID   
+fi
 ##source ./version
 ##TODO:re-enable wct after proper fix
 ##echo "Saving execution time"
diff --git a/templates/run_hf_mpi.sl.template b/templates/run_hf_mpi.sl.template
--- a/templates/run_hf_mpi.sl.template
+++ b/templates/run_hf_mpi.sl.template
@@ -13,4 +13,11 @@ srun python  $BINPROCESS/hfsims-stats-mpi.py {{hf_sim_dir}} {{hf_option}}
 date
 
 timestamp=`date +%Y%m%d_%H%M%S`
-echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} HF completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+#test before update
+res=`$gmsim/deploy/slurm_gm_workflow/scripts/test_hf.sh {{sim_dir}} {{hf_run_name}} {{srf_name}}`
+if [[ $? == 0 ]]; then
+    #passed
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} HF completed --j $SLURM_JOBID" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+else
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} HF failed --j $SLURM_JOBID --error '$res'" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+fi
