Work on seperate im_calc submit script and slurm template for simulation workflow.

diff --git a/templates/sim_im_calc.sl.template b/templates/sim_im_calc.sl.template
--- a/templates/sim_im_calc.sl.template
+++ b/templates/sim_im_calc.sl.template
@@ -12,52 +12,40 @@ echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_loca
 
 # Run the script
 start_time=`date +$runtime_fmt`
-time python $IMPATH/calculate_ims.py {{sim_dir}}/Acc/BB.bin b -o {{sim_dir}}/../IM_calc/ -np {{np}} -i {{sim_name}} -r {{fault_name}} -c {{comp}} -t s {{extended}} {{simple}}
+time python $IMPATH/calculate_ims.py {{sim_dir}}/BB/Acc/BB.bin b -o {{sim_dir}}/IM_calc/ -np {{np}} -i {{sim_name}} -r {{fault_name}} -c {{component}} -t s {{extended}} {{simple}}
 end_time=`date +$runtime_fmt`
 
-    # Test before update mgmt_db
-    res=`python $gmsim/workflow/scripts/im_calc_checkpoint.py {{mgmt_db_location}}/Runs {{sim_name}} --t s --v `
-    # Update mgmt_db
-    # Passed
-    if [[ $? == 0 ]]; then
-        timestamp=`date +%Y%m%d_%H%M%S`
-        echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation completed --run_name {{sim_name}} --force" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+# Test before update mgmt_db
+res=`python $gmsim/workflow/scripts/im_calc_checkpoint.py {{mgmt_db_location}}/Runs {{sim_name}} --t s --v
 
-        #save metadata for collection
-        # TODO:fix the weird naming
-        if [[ ! -d {{sim_dir}}/ch_log ]]; then
-            mkdir {{sim_dir}}/ch_log
-        fi
-        # TODO: adjust this temporary code to use the update_db once merged
-        cd {{mgmt_db_location}}/Runs/{{fault_name}}/{{sim_name}}
-        fd_name=`python -c "from qcore import utils; params = utils.load_sim_params('{{sim_dir}}/../sim_params.yaml'); print(params.FD_STATLIST)"`
-        fd_count=`cat $fd_name | wc -l`
-        psa_count=`cat {{sim_dir}}/../IM_calc/{{sim_name}}.csv | head -n 1 | grep -o pSA | wc -l`
+# Check that the result files exist
+res=0
+if [ -f {{sim_dir}}/IM_calc/{{sim_name}}.csv ] && [ -f {{sim_dir}}/IM_calc/{{sim_name}}_im_calc.info ]; then
+    res=1
+    echo "IM calculation failed, result files do not exist."
+fi
 
-        # log metadata
-        python $gmsim/workflow/metadata/log_metadata.py {{sim_dir}}/../ IM_calc cores={{np}} psa_count=$psa_count fd_count=$fd_count start_time=$start_time end_time=$end_time
-    else
-        #failed
-        echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation failed --run_name {{sim_name}} --error '$res' --force"  >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+# Update mgmt_db
+# Passed
+if [[ $? == 0 ]]; then
+    timestamp=`date +%Y%m%d_%H%M%S`
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation completed --run_name {{sim_name}} --force" >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+
+    if [[ ! -d {{sim_dir}}/ch_log ]]; then
+        mkdir {{sim_dir}}/ch_log
     fi
-{% endfor %}
-{% endif %}
+
+    fd_name=`python -c "from qcore import utils; params = utils.load_sim_params('{{sim_dir}}/sim_params.yaml'); print(params.FD_STATLIST)"`
+    fd_count=`cat $fd_name | wc -l`
+    psa_count=`cat {{sim_dir}}/IM_calc/{{sim_name}}.csv | head -n 1 | grep -o pSA | wc -l`
+
+    # log metadata
+    python $gmsim/workflow/metadata/log_metadata.py {{sim_dir}}/ IM_calc cores={{np}} psa_count=$psa_count fd_count=$fd_count start_time=$start_time end_time=$end_time
+else
+    #failed
+    echo "python $gmsim/workflow/scripts/management/update_mgmt_db.py {{mgmt_db_location}} IM_calculation failed --run_name {{sim_name}} --error '$res' --force"  >> {{mgmt_db_location}}/mgmt_db_queue/$timestamp\_$SLURM_JOBID
+fi
 
 
-{% if obs_dirs %}
-echo ___calculating observed____
-{% for obs_dir, obs_name, fault_name in obs_dirs %}
-    echo {{obs_dir}}
-	time python $IMPATH/calculate_ims.py {{obs_dir}}/*/*/accBB a -o {{obs_dir}}/../IM_calc/ -np {{np}} -i {{obs_name}} -r {{fault_name}} -c {{comp}} -t o {{extended}} {{simple}}
-{% endfor %}
-{% endif %}
 
-{% if rrup_files %}
-echo ___calculating rrups___
-{% for srf_file, srf_output, fd in rrup_files %}
-	time python $IMPATH/calculate_rrups.py -np {{np}} -o {{output_dir}}/{{srf_output}}.csv {{station_file}} {{srf_file}} {{fd}}
-{% endfor %}
-{% endif %}
-
-date
 
